<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="7F-CHENJINGJIAN" ignored="0" name="Test" tests="2" failures="1" timestamp="31 一月 2018 06:48:41 GMT" time="5.03" errors="0">
  <testcase name="testThisShouldFail" time="1.01" classname="com.testng.TestTimeout">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testng.TestTimeout.testThisShouldFail() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.TestTimeout.testThisShouldFail() didn't finish within the time-out 1000at com.testng.TestTimeout.testThisShouldFail(TestTimeout.java:13)at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- testThisShouldFail -->
  <testcase name="testThisShouldPass" time="4.001" classname="com.testng.TestTimeout"/>
</testsuite> <!-- Test -->
