<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="7F-CHENJINGJIAN" name="com.testng.TestTimeout" tests="2" failures="0" timestamp="02 二月 2018 02:11:49 GMT" time="5.006" errors="1">
  <testcase name="testThisShouldPass" time="4.001" classname="com.testng.TestTimeout"/>
  <testcase name="testThisShouldFail" time="1.005" classname="com.testng.TestTimeout">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testng.TestTimeout.testThisShouldFail() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.TestTimeout.testThisShouldFail() didn't finish within the time-out 1000at com.testng.TestTimeout.testThisShouldFail(TestTimeout.java:13)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </error>
  </testcase> <!-- testThisShouldFail -->
</testsuite> <!-- com.testng.TestTimeout -->
